using System;
using System.Xml;

class Resx2Srid
{
	static int Main(string[] arguments)
	{
		using (var reader = XmlReader.Create(arguments[0]))
		{
			Console.WriteLine("// This file was generated by resx2srid");
			Console.WriteLine();
			Console.WriteLine("partial class SRID");
			Console.WriteLine("{");
			while (reader.Read())
			{
				if (reader.NodeType == XmlNodeType.Element &&
					reader.Name == "data")
				{
					string name = reader["name"];
					Console.WriteLine("    public const string {0} = \"{0}\";", name);
				}
			}
			Console.WriteLine("}");
		}
		return 0;
	}
}
