using System;
using System.Xml;

class Resx2Srid
{
	static int Main(string[] arguments)
	{
		string classname = "SRID";
		string ns = null;
		if (arguments.Length > 1)
			classname = arguments[1];
		if (arguments.Length > 2)
			ns = arguments[2];
		using (var reader = XmlReader.Create(arguments[0]))
		{
			Console.WriteLine("// This file was generated by resx2srid");
			Console.WriteLine();
			if (ns != null)
			{
				Console.WriteLine("namespace {0}", ns);
				Console.WriteLine("{");
			}
			Console.WriteLine("partial class {0}", classname);
			Console.WriteLine("{");
			while (reader.Read())
			{
				if (reader.NodeType == XmlNodeType.Element &&
					reader.Name == "data")
				{
					string name = reader["name"];
					Console.WriteLine("    public const string {0} = \"{0}\";", name);
				}
			}
			Console.WriteLine("}");
			if (ns != null)
			{
				Console.WriteLine("}");
			}
		}
		return 0;
	}
}
